### ISSUE TITLE
Bromite

### ISSUE THREAD

**Issue by F-i-f** [neoblackxt/AnyWebView#1]
Would you mind adding the [Bromite system WebView](https://www.bromite.org/system_web_view) to the list?

**Comment by neoblackxt** [comment]
No. I think it is already added.
[About the package name
](https://github.com/bromite/bromite/wiki/Installing-SystemWebView#about-the-package-name)
[AnyWebView.java](https://github.com/neoblackxt/AnyWebView/blob/master/app/src/main/java/com/thinkdifferent/anywebview/AnyWebView.java#L123)

**Comment by alexa-v2** [comment]
@neoblackxt Developer of bromite module here

I'd like to know a little more about how this works

**Comment by neoblackxt** [comment]
> @neoblackxt Developer of bromite module here
> 
> I'd like to know a little more about how this works

Hi, alexa-v2. 
[config_webview_packages.xml](http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/res/res/xml/config_webview_packages.xml) records which webview can be used.
[SystemImpl.SystemImpl()](http://androidxref.com/9.0.0_r3/xref/frameworks/base/services/core/java/com/android/server/webkit/SystemImpl.java) parse that xml file
[WebViewUpdater.providerHasValidSignature()](http://androidxref.com/9.0.0_r3/xref/frameworks/base/services/core/java/com/android/server/webkit/WebViewUpdater.java#505) check if the webviews' signatures are vaild.
```java
505    private static boolean providerHasValidSignature(WebViewProviderInfo provider,
506            PackageInfo packageInfo, SystemInterface systemInterface) {
507        if (systemInterface.systemIsDebuggable()) {
508            return true;
509        }
510        // If no signature is declared, instead check whether the package is included in the
511        // system.
512        if (provider.signatures == null || provider.signatures.length == 0) {
513            return packageInfo.applicationInfo.isSystemApp();
514        }
515        if (packageInfo.signatures.length != 1) return false;
516
517        // Return whether the package signature matches any of the valid signatures
518        for (Signature signature : provider.signatures) {
519            if (signature.equals(packageInfo.signatures[0])) return true;
520        }
521        return false;
522    }
```
So I hooked this method and made it always return true.

**Comment by MarS10** [comment]
I checked it doesnt work with bromite on android 6. I took WebViewGoogle module and changed package name of webview to com.android.webview and now it works.

**Comment by arifzeeshan** [comment]
Support for Android 10? 
Installed on Android 10, but can't install Bromite Webview says "App cant be installed".

**Comment by alexa-v2** [comment]
> Support for Android 10?
> Installed on Android 10, but can't install Bromite Webview says "App cant be installed".

On Android 10 a Webview **must** Target sdk29. As of yet bromite and upstream chromium only Target sdk28

In addition to that if you already have a package called `com.android.webview` in your system signature mismatch will occur and it'll refuse to install

**Comment by markozajc** [comment]
Bromite seems to have started using `org.bromite.webview` for their package name, which I added in #3.
