### ISSUE TITLE
No "native" Chrome in Experimental 

### ISSUE THREAD

**Issue by gjf** [neoblackxt/AnyWebView#12]
v1.2 "experimental" does not show "Chrome" (I mean native Chrome, not Android System Wevbview) in webview settings while v1.1 does.
Not too critical but whatever.

If any additional information is necessary - let me know what you need.

![Screenshot 2023-07-20 121020](https://github.com/neoblackxt/AnyWebView/assets/322186/6367beb6-9daf-4e8a-9871-172f26a96aa8)

**Comment by neoblackxt** [comment]
I'm not sure. This may be a bug in the v1.1 release. In other words, chrome should not be displayed.
Refer to:
[Google Chrome app is no longer the WebView provider in Android 10](https://www.xda-developers.com/google-chrome-no-longer-webview-provider-android-10/) 
[Understanding WebView Channels](https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/channels.md)

**Comment by gjf** [comment]
> I'm not sure. This may be a bug in the v1.1 release. In other words, chrome should not be displayed. Refer to: [Google Chrome app is no longer the WebView provider in Android 10](https://www.xda-developers.com/google-chrome-no-longer-webview-provider-android-10/) [Understanding WebView Channels](https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/channels.md)

I don't know actually. Just explaining what I expect to see - and what I see. Actually "Chrome" is mentioned even on your screenshots )))

If it is a bug - you'd better remove it from there to avoid misunderstanding.

**Comment by neoblackxt** [comment]
It should not be simply removed, as some versions of Chrome should be displayed on some Android versions. This involves complex historical legacy issues in webview.

**Comment by vvb2060** [comment]
I think your module has given users a misunderstanding.
https://github.com/LSPosed/LSPosed/issues/2767#issuecomment-1732324345
Try explaining to the user that chrome is no longer a webview?

**Comment by Dimon-015** [comment]
> I think your module has given users a misunderstanding. [LSPosed/LSPosed#2767 (comment)](https://github.com/LSPosed/LSPosed/issues/2767#issuecomment-1732324345) Try explaining to the user that chrome is no longer a webview?

Other applications work fine with Chrome's webview on AnyWebView version 1.1. I simply won't use your repository anymore, that's all. If you don't want to solve the issues, it's your choice.

**Comment by vvb2060** [comment]
You may be talking about custom tabs, Try an app that actually use webview, like https://play.google.com/store/apps/details?id=mark.via.gp

**Comment by Dimon-015** [comment]
> You may be talking about custom tabs, Try an app that actually use webview, like https://play.google.com/store/apps/details?id=mark.via.gp

It won't launch for me

**Comment by Dimon-015** [comment]
> > > You may be talking about custom tabs, Try an app that actually use webview, like https://play.google.com/store/apps/details?id=mark.via.gp
> > 
> > 
> > It won't launch for me
> 
> Hi! Developers of WebView Manager here, a different approach to what AnyWebView does.
> 
> Like mentioned above, chrome on 10+ cannot function as a WebView. In fact, chrome on those Android versions completely ships without the WebView components due to the new "Trichrome library". Without getting too complicated, there are three apps, chrome, WebView, and shared code (the actual Trichrome library). All three have to be present, and only the WebView component can function as a WebView now.
> 
> AnyWebView might let you select chrome but that doesn't mean it'll work, unfortunately.
> 
> Apps access WebView via the AndroidX WebView library. We don't actually interact with lower level parts of WebView, so we can't "fix" an issue that is created by using an invalid WebView provider.
> 
> Hope this clears things up!

Just for your information, I have two applications that developers added support for Chrome's webview upon my request. So it is possible. However, if you choose not to do so, it is entirely your decision. I just provided this information for general knowledge.

**Comment by neoblackxt** [comment]
> I think your module has given users a misunderstanding. [LSPosed/LSPosed#2767 (comment)](https://github.com/LSPosed/LSPosed/issues/2767#issuecomment-1732324345) Try explaining to the user that chrome is no longer a webview?

Good proposal.
