### ISSUE TITLE
Request: add other Chromium browsers

### ISSUE THREAD

**Issue by G-D-B-9-9** [neoblackxt/AnyWebView#15]
Vivaldi, Edge, Kiwi browser, Opera, Via Browser and even Yandex?

https://github.com/kiwibrowser/src.next

https://github.com/tuyafeng/Via

**Comment by neoblackxt** [comment]
None of them is a system webview. Refer to learn more section in Readme.

**Comment by G-D-B-9-9** [comment]
FOSS Browser is also a WebView. Small app. Has adblocking and other features. 

https://github.com/T8RIN/browser

https://github.com/scoute-dich/browser/

It's on F-Droid

**Comment by neoblackxt** [comment]
> FOSS Browser is also a WebView. Small app. Has adblocking and other features. 
> 
> https://github.com/T8RIN/browser
> 
> https://github.com/scoute-dich/browser/
> 
> It's on F-Droid

It is a browser, not a webview. A webview would hava code similar to the following in its AndroidManifest.xml
```
<meta-data android:name="com.android.webview.WebViewLibrary"
                       android:value="{{ webview_lib }}" />
```
