### ISSUE TITLE
Vanadium, Mulch and any other Chromium based system webviews support.

### ISSUE THREAD

**Issue by xplshn** [neoblackxt/AnyWebView#8]
Could you add support for Vanadium Webview? Binaries here: https://gitlab.com/grapheneos/platform_external_vanadium/-/tree/13/prebuilt/arm64 also, for Mulch webview? https://github.com/GitGitro/AnyWebView this fork has support for Mulch added, but not for Vanadium.

**Comment by kgursu** [comment]
Yes, this would be handy, if you add support to them.

**Comment by neoblackxt** [comment]
This is an EXPERIMENTAL build. Please backup your data before trying it. [atifact.zip](https://github.com/neoblackxt/AnyWebView/suites/12596495078/artifacts/673785304)

**Comment by Venderbad** [comment]
> This is an EXPERIMENTAL build. Please backup your data before trying it. [AnyWebView_1.2_experimental.apk](https://github.com/neoblackxt/AnyWebView/releases/tag/v1.2)

Thank you! Works perfectly on my device👍🎉
